spring.application.name=PRICING-SERVICE

spring.config.import=configserver:http://localhost:8888

# \u2705 Neon DB Config
spring.datasource.url=jdbc:postgresql://ep-lingering-waterfall-ahk3pu5w-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NUa9e3wlkQFc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9091
