spring.application.name=CART-SERVICE

spring.config.import=configserver:http://localhost:8888

# \u2705 Neon DB Config
spring.datasource.url=jdbc:postgresql://ep-lingering-waterfall-ahk3pu5w-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NUa9e3wlkQFc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9093


# \u2705 Resilience4j
resilience4j.circuitbreaker.instances.cartservice.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.cartservice.slidingWindowSize=5
resilience4j.circuitbreaker.instances.cartservice.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cartservice.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cartservice.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cartservice.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.cartservice.eventConsumerBufferSize=10

resilience4j.circuitbreaker.instances.sampleService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.sampleService.sliding-window-type=COUNT_BASED

management.endpoints.web.exposure.include=*